### PR TITLE
[BrokenLinksH2] Fix path in link

### PR DESCRIPTION
**Pull request by DhurataJ**
Removing links, external target deprecated

### CODE REVIEW

**Comment by DhurataJ** [comment]
**Global effort to fix broken links**

@mimcco - The Content & Learning team is fixing broken links on docs.microsoft.com for the rest of H2. This effort will eliminate potential accessibility, security, and usability issues. This PR includes only link fixes and does not change other content. I'd very much appreciate your timely review and feedback on the link changes I've suggested. Thanks!

**Comment by DhurataJ** [comment]
@mattwojo - Please can you timely review and feedback on the link changes I've suggested. Thanks!

**Comment by mattwojo** [comment]
Hi @DhurataJ and @LinChristie - 
I just took a look at this update. It appears that you are removing the uservoice links, but haven't removed the call to action pointing readers to these links:

> "If you have a feature request for Configuration Manager or Intune, UserVoice is still the best place for feature requests."

Is there a different place to point customers to file feature requests @LinChristie?

image

**Comment by LinChristie** [comment]
@mattwojo Can I retire the whole page?

**Comment by mattwojo** [comment]
@LinChristie - Absolutely. Could you take a look through the entire Microsoft Collaborate content set and let me know what should be retired / removed and what still has value and should be maintained?

**Comment by mattwojo** [comment]
Can everything from that connect-redirect.md page be removed?

**Comment by LinChristie** [comment]
Please help to remove the whole page: https://docs.microsoft.com/en-us/collaborate/connect-redirect

I had a review when we took over Collaborate. I didn't aware this page existed until now. It's for someone try to access the legacy Connect website. That's why I think we don't need this anymore. The migration from Sysdev/Connect to Collaborate was already 5 years ago.

**Comment by mattwojo** [comment]
@LinChristie - Ahh, I see. Thank you. I will remove the page. Is there any other content in the Collaborate docs that should be retired and removed? Or everything else is up to date?

**Comment by LinChristie** [comment]
Other part should be fine for now. Thank you. 👍

**Pull request merged**
